version: "3"

services:
  blinkpdf:
    restart: always
    container_name: blinkpdf
    build:
      context: ./
      args:
        - PASSWORD=PASSWORD_14000
    ports:
      - "14000:5111"
      - "14022:22"
    volumes:
      - ./flag.txt:/flag.txt:ro
